Tca setup
Mindera/MinderaPeople-iOS pull request #2
Opened 2022-10-20 23:16 UTC by pedroseruca

Imported TCA module.
Added a root view under TCA guidelines, with a simple dummy button which navigates forward in the stack.

This is an experiment to understand how TCA and SwiftUI link up.

2022-10-26 10:51 UTC, p4checo requested changes
Nice one! 🙌🏼 Some suggestions related with using latest TCA and code style (I'm assuming we will follow https://github.com/Mindera/swift-style-guide 😇)

2022-10-26 10:51 UTC, p4checo commented on MinderaPeople/Screens/RootView.swift
> +//  RootView.swift
we could probably get rid of these, by creating a `IDETemplateMacros.plist` inside the `xcshareddata` of our project/workspace. I think we only have a project for now, but might be a good idea to create a workspace.

The file's contents could be:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
    Text macros reference:
    https://help.apple.com/xcode/mac/9.0/index.html?localePath=en.lproj#/dev91a7a31fc
    https://help.apple.com/xcode/mac/9.0/index.html?localePath=en.lproj#/dev7fe737ce0

    Examples:
    https://oleb.net/blog/2017/07/xcode-9-text-macros/
-->
<plist version="1.0">
<dict>
    <key>FILEHEADER</key>
    <string></string>
</dict>
</plist>
```

2022-10-26 10:51 UTC, p4checo commented on MinderaPeople/Screens/RootView.swift
> +struct AppState: Equatable {
I think that we should use the latest TCA idiom which uses `ReducerProtocol` and a new dependency management system. 

You can take a look at the relevant (free) episodes which explain it nicely:
- https://www.pointfree.co/episodes/ep201-reducer-protocol-the-problem
- https://www.pointfree.co/episodes/ep208-reducer-protocol-in-practice

2022-10-26 10:51 UTC, p4checo commented on MinderaPeople/Screens/RootView.swift
> +    case .homePageDismiss:
missing newline between multiline cases 🚓

2022-10-26 10:51 UTC, p4checo commented on MinderaPeople/MinderaPeopleApp.swift
> +                    initialState: state,
this seems to fit a single line (120 chars) 💅🏼

2022-10-26 10:51 UTC, p4checo commented on MinderaPeople/Screens/RootView.swift
> +                    isPresented: viewStore.binding(
shouldn't `.binding(` be on the next line? 🤔

2022-10-26 10:51 UTC, p4checo commented on MinderaPeople/Screens/RootView.swift
> +
spacing between views is not consistent 💅🏼

2022-10-26 12:19 UTC, asos-tiagoveloso approved these changes
Looks good to me, awesome kick start.
But I do agree with @p4checo's suggestions

2022-11-02 16:36 UTC, pedroseruca commented on MinderaPeople/MinderaPeopleApp.swift
> +                    initialState: state,
done

2022-11-02 16:36 UTC, pedroseruca commented on MinderaPeople/Screens/RootView.swift
> +                    isPresented: viewStore.binding(
done

2022-11-02 17:44 UTC, pedroseruca commented on MinderaPeople/Screens/RootView.swift
> +//  RootView.swift
done

2022-11-03 17:59 UTC, p4checo approved these changes
Great stuff! Just some minor tweaks here and there 🤓

2022-11-03 17:59 UTC, p4checo commented on MinderaPeople/Screens/RootView.swift
> +//
sadly we can't remove this `//` and newline automatically, so can you please remove it manually?

(same for other files)

2022-11-03 17:59 UTC, p4checo commented on MinderaPeople/MinderaPeopleApp.swift
> +            RootView(store: .init(initialState: .init(), reducer: feature.body))
do we need to pass in the `.body`? (same case in the previews)

2022-11-03 17:59 UTC, p4checo commented on MinderaPeople/Screens/RootView.swift
> +struct RootFeature: ReducerProtocol {
any particular reason to call it `RootFeature` and not just `Root`?

2022-11-06 18:25 UTC, pedroseruca commented on MinderaPeople/Screens/RootView.swift
> +//
done

2022-11-06 18:25 UTC, pedroseruca commented on MinderaPeople/MinderaPeopleApp.swift
> +            RootView(store: .init(initialState: .init(), reducer: feature.body))
done

2022-11-06 18:27 UTC, pedroseruca commented on MinderaPeople/Screens/RootView.swift
> +struct RootFeature: ReducerProtocol {
change name to RootReducer, conforming to some example from isoWords project

2022-11-08 10:29 UTC, merged