[MPA-9] Add biometric authentication functionality.
Mindera/MinderaPeople-iOS pull request #3
Opened 2022-11-15 12:30 UTC by madalinaardelean

Corresponding ticket: Ticket: [MPA-9](https://mindera.atlassian.net/browse/MPA-9). 

I created the `BiometricAuthenticatorClient` as an independent dependency which can be later used in different areas of the app: starting screen, settings screen (to enable/disable the feature) and so on.

I also created a dependency for the `UserDefaults`, `UserDefaultsClient`, which we should use from now on wherever needed. 

`LocalAuthenticatorView` and `BiometricAuthenticationFeature` are added just for testing purposes, will be removed

2022-11-19 16:41 UTC, pedroseruca commented on MinderaPeople/Dependencies/UserDefaultsClient/UserDefaultsClient.swift
> +    }
not sure about this here... don't love that we have on the same object very abstract logic (value for bool, value for data, etc) and at the same time logic specifically to our userDefaults keys. 

I imagine that if I exported this to a package, I will get the biometric stuff which I might not want.

2022-11-19 16:42 UTC, pedroseruca commented on MinderaPeople/Screens/AuthenticationDebugView/BiometricAuthenticationFeature.swift
> +                    await biometricAuthenticator.setAuthenticationTimeLimit(300)
does this configure the biometricAuthenticator for the whole app? or just in this context?

2022-11-19 16:43 UTC, pedroseruca approved these changes

2022-11-19 16:44 UTC, pedroseruca commented
Looks great! if we have time, we could start on some basic test, just to makes sure this is the proper way to do the `.noop` etc

2022-11-19 16:59 UTC, pedroseruca commented on MinderaPeople/Dependencies/BiometricAuthenticatorClient/BiometricAuthenticatorClientTestKey.swift
> +}
I would move this to `BiometricsAuthenticatorClient` file

2022-11-21 08:44 UTC, madalinaardelean commented on MinderaPeople/Screens/AuthenticationDebugView/BiometricAuthenticationFeature.swift
> +                    await biometricAuthenticator.setAuthenticationTimeLimit(300)
It configures it for the whole app.

2022-11-21 08:54 UTC, madalinaardelean commented on MinderaPeople/Dependencies/UserDefaultsClient/UserDefaultsClient.swift
> +    }
I wasn't very convinced by this approach, that's why I needed an extra opinion. My concern would be when we will have more stuff to save in user defaults, this file can end up pretty big. What do you think about extending the `UserDefaultsClient` by each specific client that might use it, something like this:
```swift
BiometricAuthenticatorClientPersistance.swift

private enum UserDefaultsKeys {
...
}

extension UserDefaultsClient {
    public var isBiometricAuthenticationEnabled: Bool {
        boolForKey(biometricAuthenticationEnabled)
    }

    public func setBiometricAuthenticationEnabled(_ bool: Bool) async {
        await setBool(bool, biometricAuthenticationEnabled)
    }

    public var lastBiometricAuthenticationDate: Date? {
        dateForKey(lastBiometricAuthenticationDateKey)
    }

    public func setLastBiometricAuthenticationDate(_ date: Date?) async {
        await setDate(date, lastBiometricAuthenticationDateKey)
    }
}
```

2022-11-21 17:14 UTC, pedroseruca commented on MinderaPeople/Dependencies/UserDefaultsClient/UserDefaultsClient.swift
> +    }
`UserDefaults+BiometricAuthenticator.swift`
seems better to me also

2022-11-29 15:42 UTC, p4checo reviewed
Great stuff! A few suggestions 🤓

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Dependencies/BiometricAuthenticatorClient/BiometricAuthenticatorClientLiveKey.swift
> +                    localizedReason: "We need to verify your identity"
missing proper localization

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Dependencies/BiometricAuthenticatorClient/BiometricAuthenticatorClientLiveKey.swift
> +    case userCancelled(String)
why propagate `String`s instead of the underlying errors? IMO we lose information this way

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Dependencies/BiometricAuthenticatorClient/BiometricAuthenticatorClientPersistance.swift
> +import Foundation
this file's name seems a bit off, perhaps `UserDefaultsClient+BiometricAuthenticatorClient`, as these are extensions on `UserDefaultsClient` to serve `BiometricAuthenticatorClient`?

(Also Persistence was misspelled)

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Dependencies/BiometricAuthenticatorClient/BiometricAuthenticatorClientPersistance.swift
> +private enum UserDefaultsKeys: String {
perhaps a caseless `enum` with static strings? This enum won't be instantiated anyway, and that way we avoid all the `.rawValue`s 💄

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Dependencies/UserDefaultsClient/UserDefaultsClientTestKey.swift
> +}
since we're getting some inspiration from isowords, why not copy the whole thing? These [helpers](https://github.com/pointfreeco/isowords/blob/bb0a73d20495ca95167a01eeaaf591a540120ce2/Sources/UserDefaultsClient/TestKey.swift#L34-L48) seem useful for Unit Tests

Also, when we get so much "inspiration" from another place, it's good practice to at least leave a comment with some credits/kudos to the original authors/repo/tweet/blog/etc.

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Screens/AuthenticationDebugView/BiometricAuthenticationFeature.swift
> +        var text: String { isAuthenticated ? "Unlocked" : "Locked" }
missing localization

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Screens/AuthenticationDebugView/BiometricAuthenticationFeature.swift
> +                    await biometricAuthenticator.setAuthenticationTimeLimit(300)
shouldn't it be a parameter somewhere then, e.g. some environment configuration? Or at the very least a constant neatly defined in a caseless `enum Constants`?

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Screens/AuthenticationDebugView/BiometricAuthenticationFeature.swift
> +                print("Received error: \(error)")
we should implement proper logging provided via environment in the future

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Screens/AuthenticationDebugView/BiometricAuthenticationFeature.swift
> +                    if !enabled {
perhaps a `guard` would be easier to follow? 💅🏼

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Screens/AuthenticationDebugView/BiometricAuthenticationFeature.swift
> +                    await biometricAuthenticator.updateLastSuccessfulAuthenticationDate(authenticated ? Date() : nil)
`Date()` should come from the environment as a closure `var currentDate: () -> Date` or something, since it's an external dependency and also like it is it would make proper testing difficult/impossible.

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Screens/AuthenticationDebugView/LocalAuthenticatorView.swift
> +                Toggle("Enable biometric authentication",
indentation seems off, also localization 🚓

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Screens/AuthenticationDebugView/LocalAuthenticatorView.swift
> +                viewStore.send(.authenticate)
why do we need to send two actions on the same event? Couldn't the reducer trigger authentication on `onAppear`? Additionally, we should only authenticate if the toggle is enabled, right?

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople/Dependencies/BiometricAuthenticatorClient/BiometricAuthenticatorClientLiveKey.swift
> +            let elapsedTime = Date().timeIntervalSince(lastAuthenticationDate)
`Date()` should be a dependency

2022-11-29 15:42 UTC, p4checo commented on MinderaPeople.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSFaceIDUsageDescription = "This app wants to use your Face ID. Plaese Hit OK to activate Face ID.";
Missing localization setup

2022-11-29 17:44 UTC, p4checo requested changes
Forgot to request changes 😇

2022-12-06 14:04 UTC, madalinaardelean commented on MinderaPeople/Screens/AuthenticationDebugView/BiometricAuthenticationFeature.swift
> +        var text: String { isAuthenticated ? "Unlocked" : "Locked" }
Same as [here](https://github.com/Mindera/MinderaPeople-iOS/pull/3#discussion_r1041016913)

2022-12-06 14:05 UTC, madalinaardelean commented on MinderaPeople/Screens/AuthenticationDebugView/LocalAuthenticatorView.swift
> +                Toggle("Enable biometric authentication",
Same as [here](https://github.com/Mindera/MinderaPeople-iOS/pull/3#discussion_r1041016913) for the localization part. Fixing the indentation.

2022-12-06 14:07 UTC, madalinaardelean commented on MinderaPeople/Screens/AuthenticationDebugView/LocalAuthenticatorView.swift
> +                viewStore.send(.authenticate)
There is no particular reason for calling these 2 one after the other. I was just playing around with the setup and the authentication. This view and its corresponding reducer won't be used by our app, most probably will be removed once we manage to integrate the Biometric authentication where it belongs. I adjusted the logic for them anyways.

2022-12-06 14:07 UTC, madalinaardelean commented on MinderaPeople.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSFaceIDUsageDescription = "This app wants to use your Face ID. Plaese Hit OK to activate Face ID.";
Same as [here](https://github.com/Mindera/MinderaPeople-iOS/pull/3#discussion_r1041016913)

2022-12-06 22:17 UTC, p4checo approved these changes

2022-12-06 22:17 UTC, p4checo commented on MinderaPeople/Dependencies/BiometricAuthenticatorClient/BiometricAuthenticatorClientLiveKey.swift
> +                    localizedReason: "We need to verify your identity"
Sounds good 👍🏼

2022-12-06 22:17 UTC, p4checo commented on MinderaPeople/Dependencies/BiometricAuthenticatorClient/BiometricAuthenticatorClientLiveKey.swift
> +            let elapsedTime = Date().timeIntervalSince(lastAuthenticationDate)
I see your point, but since we're already injecting `UserDefaultsClient` which is a dependency, why not inject every dependency?  It's not a deal breaker for me, unless this eventually gets some tests. To me it's just a force of habit to inject all dependencies, even if I add default arguments afterwards 🤓

2022-12-08 15:06 UTC, madalinaardelean commented
@pedroseruca please check [this commit](https://github.com/Mindera/MinderaPeople-iOS/pull/3/commits/8109034bafff4bb44f943d764f31d1b709901ffc) for the unit testing part.

2022-12-14 15:15 UTC, pedroseruca commented on MinderaPeopleTests/Dependencies/BiometricAuthenticator/BiometricAuthenticatorTests.swift
> +        await biometricAuthenticator.setAuthenticationTimeLimit(200)
```suggestion
        let biometricAuthenticator = BiometricAuthenticator(
            authenticationContext: mockedContext,
            userDefaults: userDefaultsClient,
            referenceDate: currentDate.addingTimeInterval(205)
        )
        await biometricAuthenticator.setAuthenticationTimeLimit(200)
```

2022-12-14 15:19 UTC, pedroseruca commented on MinderaPeopleTests/Dependencies/BiometricAuthenticator/BiometricAuthenticatorTests.swift
> +
you should use setup and tearDown methods, like:
```swift

    private var mockedContext: LAContextMock!
    private var userDefaultsClient: UserDefaultsClient!
    private var currentDate: Date!

    private var sut: BiometricAuthenticator!

    override func setUp() {
        mockedContext = .init()
        userDefaultsClient = .testValue
        currentDate = Date()
    }

    override func tearDown() {
        sut = nil
        currentDate = nil
        userDefaultsClient = nil
        mockedContext = nil
    }
```

this makes sure that between test everything is reset properly

2022-12-14 15:24 UTC, pedroseruca commented on MinderaPeopleTests/Dependencies/BiometricAuthenticator/LAContextMock.swift
> +    }
some important test are missing. we want to make sure that the LAcontext is being used and providing us the real authentication right? 
so we should create a couple of variables to test and make sure this is being called

```suggestion
    
    private(set) var canEvaluatePolicyCalledCount = 0
    override func canEvaluatePolicy(_ policy: LAPolicy, error: NSErrorPointer) -> Bool {
        canEvaluatePolicyCalledCount += 1
        return canEvaluatePolicyResponse
    }
    
    private(set) var evaluatePolicyCalledCount = 0
    override func evaluatePolicy(_ policy: LAPolicy, localizedReason: String) async throws -> Bool {
        evaluatePolicyCalledCount += 1
        return evaluatePolicyResponse
    }
```

this way you can go to BiometricAuthenticatorTests and check if we have called this method...

2022-12-14 15:27 UTC, pedroseruca commented on MinderaPeopleTests/Dependencies/BiometricAuthenticator/LAContextMock.swift
> +    }
we can even get beyond and store what kind of policy are we asking and make a test to check if is the right one... 
```swift
private(set) var lastCanEvalutePolicyLAPolicy: LAPolicy!
```

2022-12-14 15:28 UTC, pedroseruca commented on MinderaPeopleTests/Dependencies/BiometricAuthenticator/BiometricAuthenticatorTests.swift
> +        await biometricAuthenticator.setAuthenticationTimeLimit(200)
check this indentation on below code

2022-12-21 19:15 UTC, madalinaardelean commented on MinderaPeopleTests/Dependencies/BiometricAuthenticator/LAContextMock.swift
> +    private(set) var canEvaluatePolicyCalled = false
I usually did it using Bools, but this way seems more reliable. Thank you, just pushed the changes.

2023-01-02 15:34 UTC, pedroseruca approved these changes

2023-01-02 15:35 UTC, merged