MPA-13: Initial fastlane setup
Mindera/MinderaPeople-iOS pull request #5
Opened 2022-11-28 11:02 UTC by madalinaardelean

Initial setup for the fastlane actions. The file will be enhanced with the upload to testflight command once the CI pipeline is setup.

2022-11-28 11:56 UTC, beloso requested changes
It's an awesome start @madalinaardelean,
I just left some cosmetic changes and fixes 💅

2022-11-28 11:56 UTC, beloso commented on fastlane/Fastfile
> +	        device: ENV["DEVICE"],
Seems there is a tab missing here

2022-11-28 11:56 UTC, beloso commented on fastlane/Fastfile
> +		match(
Ideally we should use the `sync_code_signing` name.

2022-11-28 11:56 UTC, beloso commented on fastlane/Fastfile
> +	  		)
Just a minor thing, but I prefer that `)` is always aligned with the action name.

2022-11-28 11:56 UTC, beloso commented on fastlane/Fastfile
> +	  		type:"development",
Add a space after the `:`

2022-11-28 11:56 UTC, beloso commented on fastlane/Matchfile
> +app_identifier ENV["APP_IDENTIFIER"]
add an empty newline

2022-11-28 11:56 UTC, beloso commented on fastlane/Fastfile
> +end
add an empty newline

2022-11-28 11:56 UTC, beloso commented on Gemfile
> +gem "fastlane"
Add and empty newline

2022-11-28 12:19 UTC, madalinaardelean commented on fastlane/Fastfile
> +	        device: ENV["DEVICE"],
Done, thank you.

2022-11-28 12:20 UTC, madalinaardelean commented on fastlane/Fastfile
> +		match(
Sure, changed it, thanks

2022-11-28 12:20 UTC, madalinaardelean commented on fastlane/Fastfile
> +	  		)
I aligned all of them

2022-11-28 12:20 UTC, madalinaardelean commented on fastlane/Fastfile
> +	  		type:"development",
Done

2022-11-28 12:20 UTC, madalinaardelean commented on fastlane/Fastfile
> +end
Done

2022-11-28 12:20 UTC, madalinaardelean commented on Gemfile
> +gem "fastlane"
Done

2022-11-29 17:44 UTC, p4checo requested changes
Forgot to request changes 😇

2022-12-02 09:14 UTC, madalinaardelean commented on fastlane/.env.default
> +APPLE_ID="ios@mindera.com"
I stored them all as secrets and deleted them from this file.

2022-12-02 09:28 UTC, madalinaardelean commented on fastlane/Fastfile
> +	lane :fetch_development_code_signing do
I defined them as separate functions instead of lanes. I would keep them as this because I feel like it's easier to group all the actions related to that specific goal, for ex. fetching and incrementing the build number.

2022-12-02 09:29 UTC, madalinaardelean commented on fastlane/Fastfile
> +	desc "Run all unit tests"
There isn't a specific reason for using tabs instead of spaces, but I checked and a tab is corresponding to 4 spaces, at least locally on my machine.

2022-12-02 09:30 UTC, madalinaardelean commented on fastlane/Fastfile
> +		run_unit_tests
I agree, the CI will take care of these separately, will remove them from the `beta` lane.

2022-12-02 09:33 UTC, madalinaardelean commented on fastlane/Matchfile
> +git_url("git@bitbucket.org:mindera/ios-certificates.git")
Stored them as secrets.

2022-12-02 09:39 UTC, madalinaardelean commented on fastlane/Appfile
> +app_identifier(ENV["APP_IDENTIFIER"])
Not sure I understand exactly this one, as far as I understood the purpose of this file is to define certain keys so that we don't pass them for each action individually. Maybe I misunderstood this though 🤔

2022-12-02 09:41 UTC, madalinaardelean commented
@p4checo I addressed the comments, when you get the chance let me know if this is what you had in mind.

2022-12-06 17:59 UTC, p4checo commented
A note for the future, please don't force push changes to ongoing PRs as it makes reviewing much harder, as the diff between versions is essentially lost. We can always squash before merge or use the "Squash and merge" strategy when merging the PR. Thanks! 🙏🏼

2022-12-07 10:34 UTC, madalinaardelean commented on fastlane/Fastfile
> +	desc "Run all unit tests"
Got it, I fixed it, using spaces now.

2022-12-07 15:08 UTC, p4checo requested changes
Nice one!

2022-12-07 15:08 UTC, p4checo commented on .github/workflows/CI.yml
> +    runs-on: macos-latest
please be consistent with macOS versions, this `macos-latest` is not the same as `macos-12`, currently (I know, it's a bit counter intuitive, but GH hasn't promoted 12 to be the latest yet - [source](https://github.com/actions/runner-images#available-images))

(more cases)

2022-12-07 15:08 UTC, p4checo commented on .github/workflows/CI.yml
> +      - name: Run UI tests
why not run this as a different job instead of a step? That way it can be ran concurrently with other jobs

2022-12-07 15:08 UTC, p4checo commented on .github/workflows/build_and_upload.yaml
> +     - name: Set up ruby env
is this really needed?

2022-12-09 08:16 UTC, madalinaardelean commented on .github/workflows/build_and_upload.yaml
> +     - name: Upload app-store ipa and dsyms to artifacts
I double checked why I added this, but I don't think we actually need it. Will remove it.

2022-12-12 10:58 UTC, madalinaardelean commented on .github/workflows/CI.yml
> +          fastlane run_unit_tests
If I add `bundle exec` the jobs will fail saying that it can't find `fastlane`. Please check [these failed jobs](https://github.com/Mindera/MinderaPeople-iOS/actions/workflows/CI.yml). I tried with and without the ruby setup step. If I don't add the `bundle exec` the jobs seem to be executed correctly.

2022-12-12 10:58 UTC, madalinaardelean commented on fastlane/.env.default
> +FL_APP_IDENTIFIER="com.mindera.people"
Done, I went through all the fastlane actions and applied this everywhere I could and it made sense.

2022-12-12 12:15 UTC, p4checo approved these changes

2022-12-12 12:15 UTC, p4checo commented on .github/workflows/CI.yml
> +          fastlane run_unit_tests
That's probably because `bundler` is not installed by default ([source](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode)). 

However if it works without `bundle exec` then I think we can go with it. I'm fine with it as long as we're consistent. 😉

2022-12-13 12:09 UTC, asos-tiagoveloso approved these changes

2022-12-13 12:13 UTC, merged